# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Company.create(:name=>'極洋',:code=>'1301')
Company.create(:name=>'日本水産',:code=>'1332')
Company.create(:name=>'マルハニチロホールディングス',:code=>'1334')
Company.create(:name=>'ホウスイ',:code=>'1352')
Company.create(:name=>'カネコ種苗',:code=>'1376')
Company.create(:name=>'サカタのタネ',:code=>'1377')
Company.create(:name=>'雪国まいたけ',:code=>'1378')
Company.create(:name=>'ホクト',:code=>'1379')
Company.create(:name=>'秋川牧園',:code=>'1380')
Company.create(:name=>'アクシーズ',:code=>'1381')
Company.create(:name=>'ホーブ',:code=>'1382')
Company.create(:name=>'ベルグアース',:code=>'1383')
Company.create(:name=>'ルーデン・ホールディングス',:code=>'1400')
Company.create(:name=>'エムビーエス',:code=>'1401')
Company.create(:name=>'サーラ住宅',:code=>'1405')
Company.create(:name=>'ウエストホールディングス',:code=>'1407')
Company.create(:name=>'サムシングホールディングス',:code=>'1408')
Company.create(:name=>'チャイナ・ボーチー・エンバイロメンタル・ソリューションズ・テクノロジー',:code=>'1412')
Company.create(:name=>'桧家ホールディングス',:code=>'1413')
Company.create(:name=>'ショーボランドホールディングス',:code=>'1414')
Company.create(:name=>'ミライト・ホールディングス',:code=>'1417')
Company.create(:name=>'インターライフホールディングス',:code=>'1418')

Topic.create(:title=>'極洋')
Topic.create(:title=>'日本水産')
Topic.create(:title=>'マルハニチロホールディングス')
Topic.create(:title=>'ホウスイ')
Topic.create(:title=>'カネコ種苗')
Topic.create(:title=>'サカタのタネ')
Topic.create(:title=>'雪国まいたけ')
Topic.create(:title=>'ホクト')
Topic.create(:title=>'秋川牧園')
Topic.create(:title=>'アクシーズ')
Topic.create(:title=>'ホーブ')
Topic.create(:title=>'ベルグアース')
Topic.create(:title=>'ルーデン・ホールディングス')
Topic.create(:title=>'エムビーエス')
Topic.create(:title=>'サーラ住宅')
Topic.create(:title=>'ウエストホールディングス')
Topic.create(:title=>'サムシングホールディングス')
Topic.create(:title=>'チャイナ・ボーチー・エンバイロメンタル・ソリューションズ・テクノロジー')
Topic.create(:title=>'桧家ホールディングス')
Topic.create(:title=>'ショーボランドホールディングス')
Topic.create(:title=>'ミライト・ホールディングス')
Topic.create(:title=>'インターライフホールディングス')
